# Tên của workflow
name: Fetch User Data from Google Drive

# Kích hoạt workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *' # Chạy mỗi 6 giờ

# Các công việc
jobs:
  fetch-and-commit-user-data:
    runs-on: ubuntu-latest

    # === THÊM PHẦN NÀY ĐỂ CẤP QUYỀN GHI ===
    permissions:
      contents: write
    # ==========================================

    steps:
      # Bước 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Bước 2: Tải file data_web.json
      - name: Download user data from Google Drive
        run: |
          # Dùng ID file từ fetch-data.txt của bạn
          curl -L "https://drive.google.com/uc?export=download&id=1404085uVa15Hw10VGUp46b0zw0Rix35m" -o data_web.json
          echo "File data_web.json đã được tải về thành công."

      # Bước 3: Commit và push nếu có thay đổi
      - name: Commit and push if user data changed
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data_web.json
          # Chỉ commit khi file có sự thay đổi
          if ! git diff --staged --quiet; then
            git commit -m "chore: Cập nhật dữ liệu người dùng (data_web.json)"
            git push
          else
            echo "Dữ liệu người dùng không có gì thay đổi."
          fi
