# Tên của workflow, sẽ hiển thị trong tab "Actions" của repo
name: Fetch Data from Google Drive

# Cấu hình khi nào workflow sẽ được kích hoạt
on:
  # Chạy mỗi khi có push lên nhánh 'main'
  push:
    branches:
      - main
  # Cho phép chạy thủ công từ tab Actions
  workflow_dispatch:
  # Chạy theo lịch trình (ví dụ: mỗi 6 tiếng một lần) để cập nhật dữ liệu
  schedule:
    - cron: '0 */6 * * *' # Chạy vào phút thứ 0, mỗi 6 giờ

# Các công việc (jobs) sẽ được thực thi
jobs:
  # Tên của job, có thể đặt tùy ý
  fetch-and-process-data:
    # Sử dụng máy ảo Ubuntu phiên bản mới nhất để chạy job
    runs-on: ubuntu-latest

    # Các bước (steps) sẽ được thực hiện tuần tự
    steps:
      # Bước 1: Checkout code từ repository của bạn vào máy ảo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Bước 2: Tải file JSON từ Google Drive
      - name: Download data from Google Drive
        # Chạy lệnh curl để tải file.
        # ID file của bạn là 1404085uVa15Hw10VGUp46b0zw0Rix35m
        run: |
          curl -L "https://drive.google.com/uc?export=download&id=1404085uVa15Hw10VGUp46b0zw0Rix35m" -o data_web.json
          echo "File data_web.json đã được tải về thành công."

      # Bước 3: Đọc và hiển thị nội dung để kiểm tra
      - name: Process JSON data with jq
        run: |
          # Kiểm tra xem file có tồn tại và có nội dung không
          echo "--- Nội dung file data_web.json ---"
          cat data_web.json
          
          # Ví dụ: Đếm số lượng đối tượng trong file JSON
          ITEM_COUNT=$(jq 'length' data_web.json)
          echo "Tổng số mục trong file: $ITEM_COUNT"
          
          # Ví dụ: Lấy tên (name) của mục đầu tiên
          FIRST_NAME=$(jq -r '.[0].name' data_web.json)
          echo "Tên của mục đầu tiên là: $FIRST_NAME"
